---
flighdeck_motd_name: web 7.4

flightdeck_groups:
  - name: "apache"

flightdeck_users:
  - name: "apache"
    group: "apache"
    home: "/var/www"

flightdeck_root_prompt: '\u@flight-deck-web:\w# '
flightdeck_user_prompt: '\u@flight-deck-web:\w$ '

flightdeck_run_commands: |
  if [ -n "${FLIGHTDECK_CONFIG}" ]; then
    config_file=$(mktemp "${TMPDIR:-/tmp/}$(basename $0).XXXXXXXXXXXX")
    echo "$FLIGHTDECK_CONFIG" | base64 -d > $config_file
    ansible-playbook -i /ansible/inventories/all.ini -e "@${config_file}" /ansible/run.yml
  elif [ -f "${FLIGHTDECK_CONFIG_FILE}" ]; then
    ansible-playbook -i /ansible/inventories/all.ini -e "@${FLIGHTDECK_CONFIG_FILE}" /ansible/run.yml
  elif [ -f "/config/web/flightdeck-web.yml" ]; then
    ansible-playbook -i /ansible/inventories/all.ini -e "@/config/web/flightdeck-web.yml" /ansible/run.yml
  elif [ -f "/config/web/flight-deck-web.yml" ]; then
    ansible-playbook -i /ansible/inventories/all.ini -e "@/config/web/flight-deck-web.yml" /ansible/run.yml
  elif [ -f "/secrets/flight-deck-web.yml" ]; then
    ansible-playbook -i /ansible/inventories/all.ini -e "@/secrets/flight-deck-web.yml" /ansible/run.yml
  else
    ansible-playbook -i /ansible/inventories/all.ini /ansible/run.yml
  fi

flightdeck_path:
  - "/var/www/.composer/vendor/bin"
  - "/var/www/.npm-global/bin"

flightdeck_env:
  - name: "COMPOSER_MEMORY_LIMIT"
    value: "-1"
